spring:
  profiles:
    include: config

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #DB Server 의 ip add + 3306 port 로 연결을 해야 함.
    #backend Server -> DB Server

    url: jdbc:mysql://localhost:3306/shorten_url_service
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true